spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedordb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: jcp@Adm#147
    driver-class-name: com.mysql.jdbc.Driver
